### ISSUE TITLE
Unbound variable 

### ISSUE THREAD

**Issue by jkariscodes** [djangoflow/demo-django#4]
Successfully build the image from [Dockerfile](https://github.com/djangoflow/demo-django/blob/main/base/Dockerfile) but running the container results in
`/entrypoint: line 13: POSTGRES_USER: unbound variable`
`/entrypoint: line 13: POSTGRES_USER: unbound variable`
Which is referred at: [entrypoint](https://github.com/djangoflow/demo-django/blob/14d538eb9b24cde8bfecc0240d8712b8598f5a0d/base/entrypoint#L13)

**Comment by ayushin** [comment]
This is just a general docker question for stackoverflow
